### ISSUE TITLE
Could not locate any simple equality expressions involving locally mapped foreign key columns for primary join condition 'person.person_id = staff_work_assignment.person_id' on relationship Person.staff_work_assignment.

### ISSUE THREAD

**Issue by texasrut** [casact/PCDM#4]
Running into this error.  I may have it setup wrong on my side.  My assumption is it should be working out of the box.  

This is really great by the way!  Thank you for doing it!  Cant wait to use it

**Comment by genedan** [comment]
Hi @texasrut, could you post the code that led to this exception?

**Comment by texasrut** [comment]
sorry for delayed response.  I believe the issue was with my implementation.  closing this issue.
